// Where a story lives.
//
// Articles used to be article.html?id=<id>: one page that looked its content up
// in the browser. Nothing that builds a link preview runs JavaScript, so a story
// pasted into a group chat showed the paper's name and no headline.
//
// Each article now also exists as stories/<id>.html, written by
// `npm run stories` with its real title, description and image already in the
// markup. This is the single place that knows the shape of that URL.
//
// The catch: publishing is automatic. The shared-editing service commits
// published-content.js by itself, and it cannot run Node, so a story can be live
// for readers before anything has generated its page. Linking to a page that is
// not there yet would be worse than the problem this fixes, so the list below
// records which stories actually have one. Anything not in it keeps the old
// article.html?id= link, which always works.
//
// The list is regenerated by setup/build-stories.mjs. Do not edit it by hand.
window.WL_STORY_PAGES = [
  /* BEGIN GENERATED — setup/build-stories.mjs rewrites this */
  "later-start-time-approved",
  "science-wing-opens",
  "student-government-turnout",
  "cafeteria-staff-profile",
  "robotics-build-season",
  "late-bus-editorial",
  "phone-lockers-editorial",
  "spring-style-hallways",
  "lunch-table-playlist",
  "soccer-conference-drought",
  "swim-freshman-records",
  /* END GENERATED */
];

window.WL_storyHref = function (id) {
  var slug = String(id == null ? "" : id);
  var hasPage = (window.WL_STORY_PAGES || []).indexOf(slug) !== -1;
  // Paths are relative, so a page already inside stories/ must not nest again.
  var inStories = /\/stories\//.test(location.pathname);

  if (!hasPage) {
    return (inStories ? "../" : "") + "article.html?id=" + encodeURIComponent(slug);
  }
  return (inStories ? "" : "stories/") + encodeURIComponent(slug) + ".html";
};
